<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(NodeNETTargetFramework)' == ''">net8.0</TargetFramework>
    <TargetFramework Condition="'$(NodeNETTargetFramework)' != ''">$(NodeNETTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
