<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <ProjectReference Include="../Calculator.Shared/Calculator.Shared.csproj" />
    <Compile Include="../../../../bridge/NodeNET.Display/NodeNETDisplay.cs" Link="NodeNETDisplay.cs" />
  </ItemGroup>
</Project>
